#!/bin/sh

find_dsn() {
    settings=$1

    dsn=`grep '^\$set\['\''dsn'\''\]' $settings`
    [ -z "$dsn" ] || return 0

    dsn=`grep ''\''dsn'\''\s*=>\s*' $settings`
    [ -z "$dsn" ] || return 0

    return 1
}

get_db_params () {
    settings=$1
    find_dsn $settings || return 1

    dsn=`echo $dsn | sed 's|.*//||'`
    login=`echo $dsn | sed 's|:.*||'`
    [ -z "$login" ] && return 1
    
    dsn=`echo $dsn | sed 's|.*:||'`
    password=`echo $dsn | sed 's|@.*||'`
    [ -z "$password" ] && return 1

    dsn=`echo $dsn | sed 's|.*/||'`
    database=`echo $dsn | sed 's|'\''.*||'`
    [ -n "$database" ]
}

get_db_params 'project/settings_local.php' || get_db_params 'project/settings.php' \
    && (echo "-u$login" "-p$password" "$database")

