#!/bin/bash

case $# in
    1)
        PROJECTNAME=$1
        ;;
    2)
        PROJECTNAME=$1
        ;;
    *)
        echo "Usage: $0 <name>"
        exit 1
        ;;
esac

USERNAME=`whoami`
SECRET=`cat /dev/urandom | tr -dc A-Za-z0-9 | head -c 40`

git clone https://github.com/andy128k/ipf-project-template.git $PROJECTNAME

cd $PROJECTNAME
mkdir htdocs/media/upload
chmod 0777 htdocs/media/upload
mkdir tmp
chmod 0777 tmp

sed -i "s/<username>/$USERNAME/g" composer.json
sed -i "s/<projectname>/$PROJECTNAME/g" composer.json
sed -i "s/<projectname>/$PROJECTNAME/g" project/settings.php
sed -i "s/<secret>/$SECRET/g" project/settings.php

composer update

cp project/vendor/andy128k/ipf/index.php htdocs/

rm -rf .git
git init
git add .
git commit -m 'initial commit'

echo ''
echo IPF Project $PROJECTNAME was successfully created.

