#!/bin/sh

pack_uploads () {
    cd htdocs/media
    tar -cf ../../upload.tar upload
    cd ../..
}

pack_uploads
ipf-db-dump
rm -f working-data.tar
tar -cf working-data.tar upload.tar dump.sql
rm -f upload.tar dump.sql

