#!/bin/sh

pack_uploads () {
    cd htdocs/media
    tar -cf ../../upload.tar upload
    cd ../..
}

get_db_params () {
    settings=$1
    dsn=`grep '^\$set\['\''dsn'\''\]' $settings`
    if [ -n "$dsn" ]
    then
        dsn=`echo $dsn | sed 's|.*//||'`
        login=`echo $dsn | sed 's|:.*||'`
        dsn=`echo $dsn | sed 's|.*:||'`
        password=`echo $dsn | sed 's|@.*||'`
        dsn=`echo $dsn | sed 's|.*/||'`
        database=`echo $dsn | sed 's|'\''.*||'`
        [ -n $login ] && [ -n $password ] && [ -n $database ]
    else
        false
    fi
}

dump_db () {
    get_db_params 'project/settings_local.php' || get_db_params 'project/settings.php'
    mysqldump -u$login -p$password $database > dump.sql
}

pack_uploads
dump_db
rm working-data.tar
tar -cf working-data.tar upload.tar dump.sql
rm upload.tar dump.sql

